# Generated by Django 5.2.1 on 2025-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], max_length=10)),
                ('turma', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
