# Generated by Django 5.2.1 on 2025-05-22 23:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateField(default=datetime.datetime(2025, 5, 29, 23, 16, 51, 333443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
