# Generated by Django 5.2.1 on 2025-06-04 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_emprestimo_data_devolucao_prevista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='tipo',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao_prevista',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 22, 23, 19, 367824, tzinfo=datetime.timezone.utc)),
        ),
    ]
